### ISSUE TITLE
Missing Aimed Shot castbar icon

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [obble/modui#58] opened 2016-12-13 19:44 UTC
The castbar isnt showing the aimed shot icon when you cast it. It either is completely blank or it will show your previous casted ability icon.

**Comment by Steffen-Hadberg-Nielsen** [comment] 2016-12-16 10:56
Heres a video of it: https://youtu.be/MIE7o0mPEoc

**Comment by obble** [comment] 2016-12-16 23:38
on researching & testing this it seems like there's no default castbar for hunters using aimed shot in vanilla ~ since the game itself doesn't provide the information that the bar has shown up, the icon won't currently show.

it seems like this feature is usually re-enabled by third party addons such as [ZhunterMod](http://www.vanilla-addons.com/dls/zhuntermod/). are you using something like that currently?

**Comment by Steffen-Hadberg-Nielsen** [comment] 2016-12-17 10:02
I'm using SHunterTimers to make the Aimed Shot castbar show yeah

**Comment by obble** [comment] 2016-12-17 11:19
i've fixed the issue with the castbar icon not showing up by adding it to the small table of spells which manually require icons applying to them (fishing, cooking etc.). 

as far as i can tell from testing the issue with the castbar resetting is caused by SHunterTimers rather than modui, and im unable to offer any further support there.

feel free to re-open this ticket (which will be closed with the release of v77 this morning) if you want to continue to discuss.

**Comment by Steffen-Hadberg-Nielsen** [comment] 2016-12-17 12:18
Back when I played on nost 1.0 I used oCB as castbar which worked perfectly with SHunterTimers, I just tried to install it again and it didnt reset it upon spamming the ability: https://youtu.be/AdexpsKzoAI

Maybe you could take a look at oCB and see how it fixes this issue http://addons.us.to/addon/ocb-0
Would be much appreciated if you could fix this

**Comment by obble** [comment] 2016-12-17 12:25
oCB is a complete replacement for the castbar, with code support added within SHunterTimers itself. it totally rewrites the default code for the casting display bar, where the conflict exists.

unfortunately I don't have any intention to totally rewrite the castbar for a minor issue introduced by an addon that isn't my own. id recommend asking within the addon community for support or suggestions in order to fix the bug, they are often happy to help.

as the aimed shot icon issue is fixed in [v77](https://github.com/obble/modui/commit/673e5b2463ee85c3aad6b7cfebfa62f68558ceb0) i'm closing this for now. thanks.

**Closed as completed by obble** 2016-12-17 12:25 UTC
