### ISSUE TITLE
Suggestion: Include debuff timers from enemyFrames [Picture]

### ISSUE THREAD

**Issue by kev41** [obble/modui#42] opened 2016-11-21 20:09 UTC
http://imgur.com/a/hwbEF

I am using a feature from the addon enemyFrames to show timers on debuffs on my uniteframes and it works very smooth with your addon.

enemyFrames github: https://github.com/zetone/enemyFrames

**Comment by obble** [comment] 2016-11-25 08:52
closing as duplicate of feature request ticket #39

**Closed as completed by obble** 2016-11-25 08:52 UTC
Labels: duplicate
