### ISSUE TITLE
Latest version is totally broken for me

### ISSUE THREAD

**Issue by johnnybgood89** [obble/modui#86] opened 2017-01-26 23:52 UTC
Latest version is totally broken for me. Its not even working for me. I need to revert to 77

**Comment by johnnybgood89** [comment] 2017-01-27 00:03
I deleted setting in WTF folder still nothing. I got some changes but not nice black frames etc, almost like vanilla like UI. Revert to v77, and paf all good

**Comment by Road-block** [comment] 2017-01-27 17:47
I believe its this [options/menu.lua line:63](https://github.com/obble/modui/blob/8b59974d4a00bd20c1a4a2b6e3d446bc6faafa00/options/menu.lua#L63) that breaks the menu and that error cascades to a bunch of other places.  
Changing it to 
```lua
menu.intro:SetText('Hello! You are using version '..version..' of |cffff6c6cmodui|r. You can find the latest version and further support on the dedicated thread on Nostalrius\' forums:')
```
will probably fix it.

**Comment by obble** [comment] 2017-01-27 19:04
i've been unable to reproduce this issue but @Road-block is correct that line 63 is incorrectly formatted.

please try updating to v81 and let me know if this solves your issue.

**Comment by iamdorus** [comment] 2017-01-27 20:53
I personally I had the same error, but it doesn't show after updating.

**Comment by AmplusNLD** [comment] 2017-01-27 20:54
I personally I had the same error, but it doesn't show after updating.

**Comment by obble** [comment] 2017-01-28 10:06
so the error is fixed?

**Comment by Road-block** [comment] 2017-01-28 12:13
> i' ve been unable to reproduce this issue but @Road-block is correct that line 63 is incorrectly formatted.
please try updating to v81 and let me know if this solves your issue.

This is truly surprising to me 😄 . Are you playing with a Mac client or something along those lines?  
I can't think of a reason for Lua to behave differently other than the linked version or the executable itself is compiled differently. *Just idle curiosity*

**Comment by obble** [comment] 2017-01-28 12:14
i am on a mac, heh.

**Comment by Road-block** [comment] 2017-01-28 12:22
It's still very strange because the [Lua manual](http://www.lua.org/manual/5.3/manual.html#3.4.10) says 

> A call of the form f'string' (or f"string" or f[[string]]) is syntactic sugar for f('string'); that is, the argument list is a single literal string.

Notice the `single literal string` part. Once you have concatenation with a variable it's no longer a single literal string. Extra info: [Lua gotchas](http://www.luafaq.org/gotchas.html#T7)  
Tbh I've seen a couple guys now use that syntactic sugar of func"arg" but I don't know why you guys do it 😝

**Comment by obble** [comment] 2017-01-30 11:12
shaking the habitual

closing this for now, thanks

**Closed as completed by obble** 2017-01-30 11:12 UTC
