### ISSUE TITLE
Frame drop when bags are opened

### ISSUE THREAD

**Issue by stokbaek** [obble/modui#4] opened 2016-01-21 10:12 UTC
Hello,

I am getting a massive dip in frames when I open oneBag. My FPS drops from 60 FPS to 30 FPS. This is only happening with modui and not other bag addons I have tried.

**Comment by obble** [comment] 2016-01-22 18:17
Looking into this further — couldn't reproduce a dip in FPS but attempting to reproduce the issue across a couple of different installs

**Comment by stokbaek** [comment] 2016-01-27 08:55
I have discovered this is only happening if I am playing on my Linux partition. This might not be something you will be able to fix and just bad emulating from wine sadly.

**Comment by obble** [comment] 2016-01-27 12:10
unfortunate — i'm going to close this for now, but please reopen if you find a solution or have additional comments. Thanks, M.

**Closed as completed by obble** 2016-01-27 12:10 UTC

**Comment by elraro** [comment] 2018-03-27 21:39
I have exactly the same problem. FPS drops when open the bag
